apiVersion: rancher.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: rancher-bootstrap
spec:
  credentials:
    source: Secret
    secretRef:
      name: rancher2-example-creds
      namespace: crossplane
      key: credentials
