apiVersion: rancher.maaraa.io/v1beta1
kind: ProviderConfig
metadata:
  name: default #rancher-bootstrap
spec:
  credentials:
    source: Secret
    secretRef:
      name: rancher-bootstrap-provider
      namespace: crossplane
      key: credentials
